In [1]:
import numpy as np

In [4]:
zeros = np.zeros((4,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
zeros @ ones

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
labes = [1,0,2,1]

In [10]:
ohe_labels = np.zeros((4,4))
ohe_labels[np.arange(4), labes] = 1 
ohe_labels

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

How to get indices of N maximum values in a NumPy array?

In [11]:
arr = np.array([1, 3, 2, 4, 5])
print(arr.argsort()[-3:][::-1])

[4 3 1]
